package com.mshz.webflux.dto;

public enum NotifAction {
    // microprocess actions
    TASK_STARTED, TASK_EXECUTED, TASK_SUBMITTED, 
    TASK_COMPLETED, TASK_CANCELED, TASK_ON_PAUSE, TASK_VALID,
    TASK_LOG_CREATED, TASK_LOG_UPDATED, TASK_ITEM_TO_CHECK,
    TASK_ITEM_CHECKED, TASK_ITEM_UNCHECKED, TASK_TO_CHECK,
    PROCESS_EXECUTED, PROCESS_CANCELED
}
